// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import ToggleSwitch from "./ToggleSwitch";
import { useMyContext } from "../context/AppContext";

function Navbar() {
  const { darkMode } = useMyContext();

  return (
    <nav className="navbar navbar-expand-lg shadow-sm" id="global-navbar">
      <div className="container-fluid">
        <Link className="navbar-brand" aria-current="page" to="/">
          Reactory
        </Link>
        <button
          className="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span className="navbar-toggler-icon"></span>
        </button>
        <div className="collapse navbar-collapse" id="navbarNavDropdown">
          <ul className="navbar-nav me-auto mb-2 mb-lg-0">
            <li className="nav-item">
              <Link className="nav-link" aria-current="page" to="/">
                Home
              </Link>
            </li>
            <li className="nav-item dropdown">
              <a
                className="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdownMenuLink"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Assignments
              </a>
              <ul
                className="dropdown-menu"
                aria-labelledby="navbarDropdownMenuLink"
              >
                <li>
                  <Link className="dropdown-item" to="/assignment/2">
                    Assignment 2
                  </Link>
                </li>
                <li>
                  <Link className="dropdown-item" to="/assignment/3">
                    Assignment 3
                  </Link>
                </li>
              </ul>
            </li>
            <li className="nav-item">
              <Link className="nav-link" aria-current="page" to="/about">
                About
              </Link>
            </li>
            <li className="nav-item">
              <Link className="nav-link" aria-current="page" to="/contact">
                Contact
              </Link>
            </li>
          </ul>
          <span className="me-3">{darkMode ? "Dark" : "Light"}</span>
          <ToggleSwitch />
        </div>
      </div>
    </nav>
  );
}

export default Navbar;
